spring:
  datasource:
    url: jdbc:mysql://localhost:3306/strikes
    username: strikes
    password: strikes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
#          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

---
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update